"""empty message

Revision ID: d02d061a8318
Revises: 
Create Date: 2019-09-19 17:33:54.193305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02d061a8318'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.create_foreign_key(None, 'post_comment', 'post', ['post_id'], ['id'])
    op.drop_column('post_comment', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comment', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.create_foreign_key(None, 'post_comment', 'photo', ['photo_id'], ['id'])
    op.drop_column('post_comment', 'post_id')
    # ### end Alembic commands ###
